CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE UNIQUE INDEX households_pkey ON public.households USING btree (id);
CREATE UNIQUE INDEX household_members_pkey ON public.household_members USING btree (household_id, user_id);
CREATE INDEX household_members_user_id_idx ON public.household_members USING btree (user_id);
CREATE UNIQUE INDEX joint_fund_config_pkey ON public.joint_fund_config USING btree (household_id, member_code);
CREATE UNIQUE INDEX joint_fund_contributions_pkey ON public.joint_fund_contributions USING btree (id);
CREATE INDEX joint_fund_contributions_household_id_period_idx ON public.joint_fund_contributions USING btree (household_id, period);
CREATE INDEX ledger_entries_household_id_owner_member_code_period_idx ON public.ledger_entries USING btree (household_id, owner_member_code, period);
CREATE UNIQUE INDEX ledger_entries_pkey ON public.ledger_entries USING btree (id);
CREATE UNIQUE INDEX expenses_pkey ON public.expenses USING btree (id);
CREATE INDEX expenses_household_id_date_idx ON public.expenses USING btree (household_id, date);
CREATE INDEX expenses_household_category_idx ON public.expenses USING btree (household_id, category_id);
CREATE UNIQUE INDEX monthly_commitments_pkey ON public.monthly_commitments USING btree (id);
CREATE UNIQUE INDEX push_subscriptions_pkey ON public.push_subscriptions USING btree (id);
CREATE UNIQUE INDEX push_subscriptions_endpoint_key ON public.push_subscriptions USING btree (endpoint);
CREATE UNIQUE INDEX reminder_settings_pkey ON public.reminder_settings USING btree (user_id, reminder_type);
CREATE UNIQUE INDEX asset_transactions_pkey ON public.asset_transactions USING btree (id);
CREATE INDEX asset_transactions_asset_id_date_idx ON public.asset_transactions USING btree (asset_id, date);
CREATE INDEX asset_transactions_category_id_idx ON public.asset_transactions USING btree (category_id);
CREATE UNIQUE INDEX assets_pkey ON public.assets USING btree (id);
CREATE UNIQUE INDEX expense_categories_pkey ON public.expense_categories USING btree (id);
CREATE UNIQUE INDEX expense_categories_name_ci ON public.expense_categories USING btree (household_id, lower(name));
CREATE UNIQUE INDEX vendors_pkey ON public.vendors USING btree (id);
CREATE UNIQUE INDEX vendors_name_ci ON public.vendors USING btree (household_id, lower(name));
CREATE UNIQUE INDEX locations_pkey ON public.locations USING btree (id);
CREATE UNIQUE INDEX locations_name_ci ON public.locations USING btree (household_id, lower(name));
CREATE UNIQUE INDEX recurring_funds_pkey ON public.recurring_funds USING btree (id);
CREATE UNIQUE INDEX asset_categories_pkey ON public.asset_categories USING btree (id);
CREATE INDEX asset_categories_household_id_asset_type_sort_order_idx ON public.asset_categories USING btree (household_id, asset_type, sort_order);
CREATE UNIQUE INDEX asset_categories_name_ci ON public.asset_categories USING btree (household_id, asset_type, lower(name));
